version: "3.8"
services:
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3002
    volumes:
      - ${APP_DATA_DIR}/data/conf:/app/conf
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
      - ${APP_DATA_DIR}/data/database:/app/database
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.sun-panel-web-redirect.redirectscheme.scheme: https
      traefik.http.services.sun-panel.loadbalancer.server.port: 3002
      # Web
      traefik.http.routers.sun-panel-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sun-panel-insecure.entrypoints: web
      traefik.http.routers.sun-panel-insecure.service: sun-panel
      traefik.http.routers.sun-panel-insecure.middlewares: sun-panel-web-redirect
      # Websecure
      traefik.http.routers.sun-panel.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sun-panel.entrypoints: websecure
      traefik.http.routers.sun-panel.service: sun-panel
      traefik.http.routers.sun-panel.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.sun-panel-local-insecure.rule: Host(`sun-panel.${LOCAL_DOMAIN}`)
      traefik.http.routers.sun-panel-local-insecure.entrypoints: web
      traefik.http.routers.sun-panel-local-insecure.service: sun-panel
      traefik.http.routers.sun-panel-local-insecure.middlewares: sun-panel-web-redirect
      # Local domain secure
      traefik.http.routers.sun-panel-local.rule: Host(`sun-panel.${LOCAL_DOMAIN}`)
      traefik.http.routers.sun-panel-local.entrypoints: websecure
      traefik.http.routers.sun-panel-local.service: sun-panel
      traefik.http.routers.sun-panel-local.tls: true