name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC 0:00执行
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Fork Sync2
      # You may pin to the exact commit or the version.
      # uses: zwping/fork-sync@7ad9681518d04008cc8f056abed8fefc2902e96d
      uses: zwping/fork-sync@v1.6.5
          
